#!/bin/sh

set -eu

TABLER_REPO_PATH="${TABLER_REPO_PATH}"
ICONS_JSON="${TABLER_REPO_PATH}/shared/data/icons.json"
ICONS_INFO_JSON="${TABLER_REPO_PATH}/shared/data/icons-info.json"
ASSETS_DIR="${ASSETS_DIR:-Sources/TablerIcons/Icons.xcassets}"
IOS_SWIFT_FILE="${IOS_SWIFT_FILE:-Sources/TablerIcons/TablerIcons+iOS.swift}"

if [ ! -f "$ICONS_JSON" ]; then
  echo "error: icons data not found: $ICONS_JSON" >&2
  echo "Set TABLER_REPO_PATH to the root of the tabler/tabler repository." >&2
  exit 1
fi

rm -rf "$ASSETS_DIR"
mkdir -p "$ASSETS_DIR"

node - "$ICONS_JSON" "$ICONS_INFO_JSON" "$ASSETS_DIR" "$IOS_SWIFT_FILE" <<'NODE'
const fs = require("fs");
const path = require("path");

const [iconsJsonPath, iconsInfoJsonPath, assetsDir, iosSwiftFile] = process.argv.slice(2);
const icons = JSON.parse(fs.readFileSync(iconsJsonPath, "utf8"));
const iconsInfo = fs.existsSync(iconsInfoJsonPath)
  ? JSON.parse(fs.readFileSync(iconsInfoJsonPath, "utf8"))
  : null;

const contentsJson = (filename) => `${JSON.stringify({
  images: [
    {
      filename,
      idiom: "universal",
    },
  ],
  info: {
    author: "xcode",
    version: 1,
  },
}, null, 2)}\n`;

const swiftName = (assetName) => assetName
  .split("-")
  .map((part, index) => index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1))
  .join("");

const writeIcon = (iconName, variant, svg) => {
  if (!svg) {
    return null;
  }

  const assetName = `${iconName}-${variant}`;
  const imagesetDir = path.join(assetsDir, `${assetName}.imageset`);
  const svgFilename = `${assetName}.svg`;

  fs.mkdirSync(imagesetDir, { recursive: true });
  fs.writeFileSync(path.join(imagesetDir, svgFilename), `${svg}\n`);
  fs.writeFileSync(path.join(imagesetDir, "Contents.json"), contentsJson(svgFilename));

  return assetName;
};

const assetNames = [];

for (const iconName of Object.keys(icons).sort()) {
  const icon = icons[iconName];
  const outlineName = writeIcon(icon.name, "outlined", icon.svg && icon.svg.outline);
  const filledName = writeIcon(icon.name, "filled", icon.svg && icon.svg.filled);

  if (outlineName) {
    assetNames.push(outlineName);
  }

  if (filledName) {
    assetNames.push(filledName);
  }
}

assetNames.sort();

const header = [
  "// This is autogenerated file",
  "// DO NOT EDIT",
];

if (iconsInfo && iconsInfo.version) {
  header.push(`// Tabler Icons version: ${iconsInfo.version}`);
}

header.push("");

const swiftLines = [
  ...header,
  "#if canImport(UIKit)",
  "import UIKit",
  "",
  "extension TablerIcons {",
  ...assetNames.map((assetName) => {
    const propertyName = swiftName(assetName);
    return `  public static let \`${propertyName}\`: UIImage = UIImage(named: "${assetName}", in: Bundle.module, compatibleWith: nil)!`;
  }),
  "}",
  "",
  "#endif",
  "",
];

fs.writeFileSync(iosSwiftFile, swiftLines.join("\n"));

const filledCount = assetNames.filter((name) => name.endsWith("-filled")).length;
const outlinedCount = assetNames.filter((name) => name.endsWith("-outlined")).length;
console.log(`Generated ${outlinedCount} outlined icons and ${filledCount} filled icons.`);
NODE

if [ "${SKIP_GIT_ADD:-0}" != "1" ] && command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git add "$ASSETS_DIR" "$IOS_SWIFT_FILE"
fi
